# Generated by Django 5.2.1 on 2025-09-09 15:29

import django.db.models.deletion
import oraw_app.models.athlete
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("year_of_birth", models.PositiveIntegerField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "public_alias",
                    models.SlugField(
                        default=oraw_app.models.athlete.generate_alias, max_length=16, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True, null=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("by", models.CharField(max_length=200)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_audit_logs",
                        to="oraw_app.athlete",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("show_name", models.BooleanField(default=False)),
                ("hide_until", models.DateField(blank=True, null=True)),
                ("suppressed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to="oraw_app.athlete",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AthleteIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("EMIT", "EMIT"),
                            ("SI", "SI"),
                            ("NAT", "National ID"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="oraw_app.athlete",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind", "value"], name="oraw_app_at_kind_c53154_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("athlete", "kind", "value"), name="uniq_identifier_per_athlete"
                    )
                ],
            },
        ),
    ]
