# Generated by Django 5.2.1 on 2025-09-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0002_competition_course_result_split_uploadedfile_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uploadedfile",
            name="oraw_app_up_competi_6a8758_idx",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="competition",
        ),
        migrations.AddField(
            model_name="competition",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Original IOFXML file this competition was created from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competitions_primary",
                to="oraw_app.uploadedfile",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="stored_file",
            field=models.FileField(blank=True, null=True, upload_to="iofxml/%Y/%m/%d"),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(fields=["sha256"], name="oraw_app_up_sha256_75cf6f_idx"),
        ),
    ]
