# Generated by Django 5.2.1 on 2025-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0004_controlcard_result_control_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="retention_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
