# Generated by Django 5.2.1 on 2025-10-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0005_uploadedfile_retention_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="club",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("X", "Other/Unspecified")],
                max_length=1,
                null=True,
            ),
        ),
    ]
