# Generated by Django 5.2.1 on 2025-10-13 06:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0006_athlete_club_athlete_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="athlete",
            options={"ordering": ["last_name", "first_name"]},
        ),
        
        
        migrations.AddField(
            model_name="athlete",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="athlete",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="athlete",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("X", "Other/Unknown")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="public_alias",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="athleteidentifier",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="athleteidentifier",
            name="kind",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="athleteidentifier",
            name="value",
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name="athlete",
            index=models.Index(
                fields=["last_name", "first_name"], name="oraw_app_at_last_na_ce9aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="athlete",
            index=models.Index(fields=["club"], name="oraw_app_at_club_9dfdbc_idx"),
        ),
        migrations.AddIndex(
            model_name="athlete",
            index=models.Index(fields=["gender"], name="oraw_app_at_gender_9f01ed_idx"),
        ),
        migrations.AddIndex(
            model_name="athleteidentifier",
            index=models.Index(fields=["athlete", "kind"], name="oraw_app_at_athlete_dd7e78_idx"),
        ),
        migrations.AddIndex(
            model_name="athleteidentifier",
            index=models.Index(fields=["value"], name="oraw_app_at_value_6b0e44_idx"),
        ),
    ]
