# Generated by Django 5.2.1 on 2025-10-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0007_alter_athlete_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="athleteidentifier",
            name="oraw_app_at_kind_c53154_idx",
        ),
    ]
