# Generated by Django 5.2.1 on 2025-10-14 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0009_alter_result_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypreference",
            options={"ordering": ["athlete"]},
        ),
        migrations.RenameField(
            model_name="auditlog",
            old_name="reason",
            new_name="details",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="by",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="data_category",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="event",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="processing_basis",
        ),
        migrations.RemoveField(
            model_name="privacypreference",
            name="hide_until",
        ),
        migrations.RemoveField(
            model_name="privacypreference",
            name="show_name",
        ),
        migrations.RemoveField(
            model_name="privacypreference",
            name="suppressed_at",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("ACCESS", "ACCESS"),
                ],
                default="UPDATE",
                max_length=12,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="privacypreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privacypreference",
            name="data_category",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="privacypreference",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privacypreference",
            name="processing_basis",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="privacypreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="oraw_app.athlete",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="privacypreference",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="privacypreference",
            index=models.Index(fields=["retention_until"], name="oraw_app_pr_retenti_08d203_idx"),
        ),
        migrations.AddIndex(
            model_name="privacypreference",
            index=models.Index(
                fields=["data_subject_request_status"], name="oraw_app_pr_data_su_6bbc6e_idx"
            ),
        ),
    ]
