# Generated by Django 5.2.1 on 2025-10-14 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0010_alter_privacypreference_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="retention_until",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="stored_file",
            field=models.FileField(default=django.utils.timezone.now, upload_to="iofxml/%Y/%m/%d"),
            preserve_default=False,
        ),
    ]
