# Generated by Django 5.2.1 on 2025-10-15 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0011_remove_uploadedfile_retention_until_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="competition",
            name="uniq_competition_name_date",
        ),
        migrations.RemoveIndex(
            model_name="competition",
            name="oraw_app_co_name_433f12_idx",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="iof_event_id",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="source_name",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="source_url",
        ),
        migrations.AddField(
            model_name="competition",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="competition",
            name="organizer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(fields=["organizer"], name="oraw_app_co_organiz_e89472_idx"),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(fields=["location"], name="oraw_app_co_locatio_6dfecf_idx"),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(fields=["source_file"], name="oraw_app_co_source__111111_idx"),
        ),
    ]
