# Generated by Django 5.2.1 on 2025-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0012_remove_competition_uniq_competition_name_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacypreference",
            name="show_name",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="privacypreference",
            index=models.Index(fields=["show_name"], name="oraw_app_pr_show_na_eda164_idx"),
        ),
    ]
