# Generated by Django 5.2.1 on 2025-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0013_privacypreference_show_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="by",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="event",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "CREATE"),
                    ("UPDATE", "UPDATE"),
                    ("DELETE", "DELETE"),
                    ("ACCESS", "ACCESS"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event"], name="oraw_app_au_event_12ec69_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["by"], name="oraw_app_au_by_ae07b1_idx"),
        ),
    ]
