# Generated by Django 5.2.1 on 2025-10-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0014_auditlog_by_auditlog_event_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="privacy_audit_logs",
                to="oraw_app.athlete",
            ),
        ),
    ]
