# Generated by Django 5.2.1 on 2025-10-17 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0015_alter_auditlog_athlete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="clazz",
        ),
        migrations.AddField(
            model_name="course",
            name="climb_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="length_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Course length in kilometers (optional).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["length_km"], name="oraw_app_co_length__2361de_idx"),
        ),
    ]
