# Generated by Django 5.2.1 on 2025-10-20 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0016_remove_course_clazz_course_climb_m_course_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="controlcard",
            name="uniq_controlcard_vendor_uid",
        ),
        migrations.RemoveIndex(
            model_name="controlcard",
            name="oraw_app_co_vendor_65bca3_idx",
        ),
        migrations.AddField(
            model_name="controlcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controlcard",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_cards",
                to="oraw_app.athlete",
            ),
        ),
        migrations.AddField(
            model_name="controlcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="controlcard",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="controlcard",
            name="vendor",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "UNKNOWN"),
                    ("EMIT", "EMIT"),
                    ("SI", "SI"),
                    ("OTHER", "OTHER"),
                ],
                default="UNKNOWN",
                help_text="Card vendor/manufacturer.",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="controlcard",
            index=models.Index(fields=["vendor"], name="oraw_app_co_vendor_15fc20_idx"),
        ),
        migrations.AddIndex(
            model_name="controlcard",
            index=models.Index(fields=["uid"], name="oraw_app_co_uid_ce3bef_idx"),
        ),
        migrations.AddConstraint(
            model_name="controlcard",
            constraint=models.UniqueConstraint(
                fields=("vendor", "uid"), name="uniq_control_card_vendor_uid"
            ),
        ),
    ]
