# Generated by Django 5.2.1 on 2025-10-21 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0019_fix_split_control_code_notnull"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="split",
            options={
                "ordering": ["result_id", "seq"],
                "verbose_name": "Split",
                "verbose_name_plural": "Splits",
            },
        ),
        migrations.RemoveIndex(
            model_name="split",
            name="oraw_app_sp_result__dd355f_idx",
        ),
        migrations.RemoveIndex(
            model_name="split",
            name="oraw_app_sp_seq_6d7cc5_idx",
        ),
        migrations.RemoveIndex(
            model_name="split",
            name="oraw_app_sp_control_247a4f_idx",
        ),
        migrations.AlterField(
            model_name="split",
            name="control_code",
            field=models.CharField(
                help_text="Control code (e.g. '31', '100', or special code)", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp (auto set)"
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="cum_time_s",
            field=models.IntegerField(
                blank=True,
                help_text="Cumulative time to this control in seconds (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID primary key for split entry",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional notes or comments for this split", null=True
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="result",
            field=models.ForeignKey(
                help_text="Link to the parent Result",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="oraw_app.result",
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="seq",
            field=models.PositiveIntegerField(
                help_text="Sequence number within result, starting from 1"
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="split_time_s",
            field=models.IntegerField(
                default=0, help_text="Leg time (delta from previous split) in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp (auto updated)"
            ),
        ),
        migrations.AddIndex(
            model_name="split",
            index=models.Index(fields=["result", "seq"], name="idx_split_result_seq"),
        ),
        migrations.AddIndex(
            model_name="split",
            index=models.Index(fields=["result", "control_code"], name="idx_split_result_code"),
        ),
        migrations.AlterModelTable(
            name="split",
            table="oraw_app_split",
        ),
    ]
