# Generated by Django 5.2.1 on 2025-11-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0020_alter_split_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [("can_import_iofxml", "Can import IOF XML result files")],
            },
        ),
    ]
