# Generated by Django 5.2.1 on 2025-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0021_alter_uploadedfile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="retention_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
