# oraw_app/migrations/0018_fix_split_and_add_unique.py
# Generated by Django 5.2.1 on 2025-10-20

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def forwards_clean_splits(apps, schema_editor):
    """
    - Fill NULL/empty control_code -> 'UNKNOWN'
    - Deduplicate (result_id, control_code): keep the oldest (smallest pk), delete the rest
    - Ensure split_time_s is integer (NULL -> 0), cum_time_s NULL ok
    """
    Split = apps.get_model("oraw_app", "Split")
    db_alias = schema_editor.connection.alias

    # 1) Tyhjät control_code -> 'UNKNOWN'
    qs_null = Split.objects.using(db_alias).filter(control_code__isnull=True)
    qs_null.update(control_code="UNKNOWN")
    qs_empty = Split.objects.using(db_alias).filter(control_code="")
    qs_empty.update(control_code="UNKNOWN")

    # 2) split_time_s ei saa olla datetime; jos on NULL, laitetaan 0.
    #    (Jos sinulla on virheellisiä arvoja, tämä normalisoi migraatiossa.)
    Split.objects.using(db_alias).filter(split_time_s__isnull=True).update(split_time_s=0)

    # 3) Poista duplikaatit (result, control_code)
    #    Kerätään kaikki pk:t per pari, jätetään pienin (vanhin), poistetaan loput.
    from collections import defaultdict

    pairs = defaultdict(list)
    for s in Split.objects.using(db_alias).only("id", "result_id", "control_code").order_by("id"):
        pairs[(s.result_id, s.control_code)].append(s.id)

    to_delete = []
    for key, ids in pairs.items():
        if len(ids) > 1:
            # jätetään ensimmäinen (pienin id), loput poistoon
            to_delete.extend(ids[1:])

    if to_delete:
        Split.objects.using(db_alias).filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("oraw_app", "0017_remove_controlcard_uniq_controlcard_vendor_uid_and_more"),
    ]

    operations = [
        # Poista vanha constraint (jos sellainen oli)
        migrations.RemoveConstraint(
            model_name="split",
            name="uniq_split_result_seq",
        ),
        # Poista vanhat kentät, jotka korvattiin uusilla
        migrations.RemoveField(
            model_name="split",
            name="leg_time_s",
        ),
        migrations.RemoveField(
            model_name="split",
            name="note",
        ),
        migrations.RemoveField(
            model_name="split",
            name="time_s",
        ),
        # Lisää uudet kentät
        migrations.AddField(
            model_name="split",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="split",
            name="cum_time_s",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="split",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="split",
            name="split_time_s",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="split",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="split",
            name="control_code",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="split",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="splits",
                to="oraw_app.result",
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="seq",
            field=models.PositiveIntegerField(),
        ),

        # *** DEDUP ENNEN UNIQUEN LISÄYSTÄ ***
        migrations.RunPython(forwards_clean_splits, migrations.RunPython.noop),

        # Nyt vasta uniikit rajoitteet
        migrations.AddConstraint(
            model_name="split",
            constraint=models.UniqueConstraint(
                fields=("result", "seq"), name="uniq_split_per_result_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="split",
            constraint=models.UniqueConstraint(
                fields=("result", "control_code"), name="uniq_split_per_result_code"
            ),
        ),
    ]
